name: Python Tests and PR Approval

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run unit tests
        run: python test_Examne2.py

      - name: Check test status and approve PR
        if: success()
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.REVIEW_TOKEN}}  # Utiliza el nuevo secreto aquí
          script: |
            github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: 'APPROVE'
            })
